title: Mike's Digital Garden
description: A personal knowledge vault
url: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: /notes/:title/

# Defaults
defaults:
  - scope:
      path: "*.md"
      type: "pages"
    values:
      layout: "post"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .obsidian/
  - README.md
  - .git
  - .gitignore
  - .vercel
  - .mcp.json
